# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(email: "email1@gmail.com", password:"123456")
user2 = User.create(email: "email2@gmail.com", password:"123456")
user3 = User.create(email: "email3@gmail.com", password:"123456")
user4 = User.create(email: "email4@gmail.com", password:"123456")
user5 = User.create(email: "email5@gmail.com", password:"123456")
user6 = User.create(email: "email6@gmail.com", password:"123456")
user7 = User.create(email: "email7@gmail.com", password:"123456")
user8 = User.create(email: "email8@gmail.com", password:"123456")
user9 = User.create(email: "email9@gmail.com", password:"123456")
user10 = User.create(email: "email10@gmail.com", password:"123456")

musician1 = Musician.create(first_name: "Claudio", last_name: "Sanchez", home_town: "Nyack, NY", email: "test@test.com", scene: "NYC", instruments: "guitar, vocals, synths", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 1)
musician2= Musician.create(first_name: "Dimitri", last_name: "Giannopoulos", home_town: "Boston, MA", email: "test@test.com", scene: "Boston", instruments: "guitar, vocals", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 2)
musician3= Musician.create(first_name: "John", last_name: "Margaris", home_town: "Boston, MA", email: "test@test.com", scene: "Boston", instruments: "bass", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 3)
musician4= Musician.create(first_name: "Jamie", last_name: "Vadala", home_town: "Boston, MA", email: "test@test.com", scene: "Boston", instruments: "drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 4)
musician5= Musician.create(first_name: "Ellen", last_name: "Kempner", home_town: "Boston, MA", email: "test@test.com", scene: "Boston", instruments: "guitar, vocals, drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 5)
musician6= Musician.create(first_name: "Jesse", last_name: "Weiss", home_town: "Boston, MA", email: "test@test.com", scene: "Boston", instruments: "drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 6)
musician7= Musician.create(first_name: "Mike", last_name: "Krol", home_town: "Milwaukee, WI", email: "test@test.com", scene: "Los Angeles, CA", instruments: "guitar, vocals, bass, drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 7)
musician8= Musician.create(first_name: "Gretchen", last_name: "Williams", home_town: "Easthampton, Massachusetts", email: "test@test.com", scene: "Boston", instruments: "guitar, vocals, bass, drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 8)
musician9= Musician.create(first_name: "Brandon", last_name: "Shaw", home_town: "Whip City, Massachusetts", email: "test@test.com", scene: "Boston", instruments: "guitar, vocals, bass, drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 9)
musician10= Musician.create(first_name: "Sidney", last_name: "Veilleux", home_town: "Charlton, Massachusetts", email: "test@test.com", scene: "Boston", instruments: "ukulele, vocals, drums", bio: "Lorem ipsum dolor sit amet, et mel duis verear, his te facilisi mnesarchum, vix omnis latine voluptaria ei. Ad stet feugait accusam duo, vel liber postea principes an. Vim ex dolorem suscipit molestiae, minimum accumsan concludaturque cu pro. Duis praesent recteque ad est, elit adipisci salutandi per at, sea nibh wisi debet ex. Tractatos deseruisse usu ea, cum modus tritani maiorum no. Eu sea diceret commune comprehensam.", user_id: 10)
